### ISSUE TITLE
Using this theme without Composer?

### ISSUE THREAD

**Issue by jbwharris** [rexrana/bootstrap-twig#1]
I'm trying to figure out how to get this theme up and running without using Composer. In the readme there's nothing mentioning it needs to be installed, but it tosses an error as soon as it finds there isn't a /vendor/autoload.php in the functions.php. I am very new to this and was just hoping to get the lay of the land of using a Twig based Bootstrap WordPress setup. I have installed the main starter template and it has a line in there about not needing Composer if I'm using the Timber plugin.

![image](https://user-images.githubusercontent.com/2962327/76427560-d80f4880-6382-11ea-9d8f-d3be7ad34049.png)

**Comment by peterhebert** [comment]
Yes currently it requires Composer to be installed, as it has dependencies managed through composer, apart from the Timber plugin, which you can install via the WordPress plugin directory. Once I get it stable, I will publish a zip release on wordpress.org. 

I'll update the docs with some Composer in the next couple of days, and update this thread once that's done.

**Comment by peterhebert** [comment]
Composer is pretty easy to get installed on your system, just follow docs at https://getcomposer.org/ (Getting Started and Download sections). Once Composer is installed, you just navigate to the plugin folder in your terminal and run `composer install`

**Comment by peterhebert** [comment]
I have now removed all Composer autoloading, as there was only one dependency for the phone number formatting functions, now moved to inc/deprecated.php, which is not included in the functions.php. Theme should work fine without composer install, as long as TImber plugin is installed on site.
